---
output: github_document
bibliography: doc/breast_cancer_refs.bib  *****
---

# "What happens in vegas: Predicting hotel ratings from amenities provided"
- author: Bronwyn Baillie , Arun Maria , Manish Joshi
- contributors: Bronwyn Baillie , Arun Maria , Manish Joshi   ????

Demo of a data analysis project for DSCI 522 (Data Science workflows); a course in the Master of Data Science program at the University of British Columbia.

## About
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(kableExtra)
library(tidyverse)
library(caret)
model_quality <- readRDS("results/final_model_quality.rds")
```

Here we attempt to build a classification model using the k-nearest neighbours algorithm which can use breast cancer tumour image measurements to predict whether a newly discovered breast cancer tumour is benign (i.e., is not harmful and does not require treatment) or malignant (i.e., is harmful and requires treatment intervention). Our final classifier performed fairly well on an unseen test data set, with Cohen's Kappa score of `r round(model_quality$overall[2], 1)` and an overall accuracy calculated to be `r round(model_quality$overall[1], 2)`. On the `r sum(model_quality$table)` test data cases, it correctly predicted  `r model_quality$table[2, 2] + model_quality$table[1, 1]`. However it incorrectly predicted  `r model_quality$table[2, 1] + model_quality$table[1, 2]` cases, and importantly these cases were false negatives; predicting that a tumour is benign when in fact it is malignant. These kind of incorrect predictions could have a severly negative impact on a patients health outcome, thus we recommend continuing study to improve this prediction model before it is put into production in the clinic. 


Here we attempt to build a linear regression model which can use data about the hotel amenities and predict what kind of user ratings can be expected for the hotel given these amenities are functional in the hotel. Our final liner model performed well on the unseen test data with a test score of ..... and an overall accuracy calculated to be ...


The Dataset chosen for the research project is the “Las Vegas Strip Dataset” which is a collated information about customer feedback on 21 Hotels located in the Las Vegas Strip. The data is extracted from popular and well-regarded travel portal “TripAdvisor”. -Moro, S., Rita, P., & Coelho, J. (2017). Stripping customers' feedback on hotels through data mining: The case of Las Vegas Strip. Tourism Management Perspectives, 23, 41-52. It was sourced from the UCI machine learning repositories and can be found [here](https://archive.ics.uci.edu/ml/datasets/Las+Vegas+Strip). Each row in the data set represents information about the amenities present in the hotel such as swimming pool, spa, wifi and other contextual data and the user rating for the hotel.


## Report
The final report can be found [here](https://ttimbers.github.io/breast_cancer_predictor/doc/breast_cancer_predict_report.html).

## Usage

To replicate the analysis, clone this GitHub repository, install the [dependencies](#dependencies) listed below, and run the following commands at the command line/terminal from the root directory of this project:

```
# download data
python src/download_data.py --out_type=feather --url=http://mlr.cs.umass.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data --out_file=data/raw/wdbc.feather

# run eda report
Rscript -e "rmarkdown::render('src/breast_cancer_eda.Rmd')"

# pre-process data 
Rscript src/pre_process_wisc.r --input=data/raw/wdbc.feather --out_dir=data/processed 

# create exploratory data analysis figure and write to file 
Rscript src/eda_wisc.r --train=data/processed/training.feather --out_dir=results

# tune model
Rscript src/fit_breast_cancer_predict_model.r --train=data/processed/training.feather --out_dir=results

# test model
Rscript src/breast_cancer_test_results.r --test=data/processed/test.feather --out_dir=results

# render final report
Rscript -e "rmarkdown::render('doc/breast_cancer_predict_report.Rmd', output_format = 'github_document')"
```




## Dependencies
- Python 3.7.3 and Python packages:
  - docopt==0.6.1
  - pandas==0.24.2
  - feather-format==0.4.0
  
- R version 3.6.1 and R packages:
  - knitr==1.26
  - feather==0.3.5
  - tidyverse==1.3
  - caret==6.0-85
  - ggridges==0.5.2
  - ggthemes==4.2.0
  - ggplot2==3.2.1
  - readr==1.3.1
  - ggally==1.4.0
  - repr==1.0.2
  - gridextra==2.3
  - reticulate==1.14
  

from docopt import docopt
import os
import matplotlib.pyplot as plt

from pandas.plotting import table
import numpy as np
import selenium

import pickle
import pandas as pd

# regressors / models
from sklearn.linear_model import LinearRegression, LogisticRegression, Lasso, Ridge

from sklearn.svm import  SVR
from sklearn.ensemble import  RandomForestRegressor

# Feature selection
from sklearn.feature_selection import RFE


# other

from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.feature_extraction.text import CountVectorizer
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import altair as alt
  
## License
The Breast Cancer Predictor materials here are licensed under the Creative Commons Attribution 2.5 Canada License (CC BY 2.5 CA). If re-using/re-mixing please provide attribution and link to this webpage.

# References